app_name = "bloomerang_erpnext"
app_title = "Bloomerang Integration"
app_publisher = "Your Name"
app_description = "Bloomerang to ERPNext migration and AI reconciliation tool"
app_email = "your.email@example.com"
app_license = "mit"